[server]
headless = true
port = 8501
enableCORS = false


[theme]
primaryColor = "#d33682"
backgroundColor = "#002b36"
secondaryBackgroundColor = "#586e75"
textColor = "#ffffff"

[client]
toolbarMode = "minimal"
